### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by mkdirlove** [McaTech-PH/.github#2]
How to contribute?

**Comment by TreacherousDev** [comment]
Hey! 

This organization was created for the newly formed in-house developers of McaTech so we can work on our internal projects. As such, repositories will have limited visibility to non-collaborators. If you are interested in becoming part of the team, it would be best to approach Sir Michael @mca192004 .

Learn more about us [here](https://www.facebook.com/profile.php?id=61564752511200).
